name: ci

on:
  pull_request:
    branches:
      - main

permissions:
  actions: read
  contents: read

env:
  NX_CLOUD_ACCESS_TOKEN: ${{ secrets.NX_CLOUD_ACCESS_TOKEN }}

jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - uses: asdf-vm/actions/install@v3

      - run: pnpm i

      - uses: ./.github/actions/set-shas
        with:
          env_name: main
          gh_token: ${{ secrets.GITHUB_TOKEN }}
          gh_sha: ${{ github.sha }}

      - run: pnpm nx affected -t lint typecheck test
