name: Publish

on:
  release:
    types: [published]

permissions:
  deployments: read
  id-token: write
  contents: read
  actions: read
  pull-requests: write

env:
  NX_CLOUD_ACCESS_TOKEN: ${{ secrets.NX_CLOUD_ACCESS_TOKEN }}
  NPM_AUTH_TOKEN: ${{ secrets.NPM_AUTH_TOKEN }}

jobs:
  build:
    environment: release
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - uses: asdf-vm/actions/install@v3

      - run: pnpm i

      - uses: ./.github/actions/set-shas
        with:
          env_name: release
          gh_token: ${{ secrets.GITHUB_TOKEN }}
          gh_sha: ${{ github.sha }}

      # build the packages
      - run: |
          pnpm nx affected -t build \
          --nxBail \
          --exclude=@warren/source

      # write the version to a file
      - run: echo ${{ github.event.release.tag_name }} > version.txt

      # publish the packages
      - run: |
          pnpm nx affected -t publish \
          --nxBail \
          --exclude=@warren/source
