name: publish

on:
  release:
    types: [published]

permissions:
  deployments: read
  id-token: write
  contents: read
  actions: read
  pull-requests: write

env:
  NX_CLOUD_ACCESS_TOKEN: ${{ secrets.NX_CLOUD_ACCESS_TOKEN }}
  NPM_AUTH_TOKEN: ${{ secrets.NPM_AUTH_TOKEN }}

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - uses: asdf-vm/actions/install@v3

      - run: pnpm i

      - uses: ./.github/actions/set-shas
        with:
          env_name: main
          gh_token: ${{ secrets.GITHUB_TOKEN }}
          gh_sha: ${{ github.sha }}

      # build the packages
      - run: |
          pnpm nx affected -t build \
          --nxBail \
          --exclude=@warren/source

      # update the version on the main package
      - run: ./bin/version-source.sh ${{ github.event.release.tag_name }}

      # update the version in the package.json of each package
      - run: |
          pnpm nx affected -t version \
          --nxBail \
          --exclude=@warren/source

      # commit the changes
      - run: |
          git commit -am "chore(publish): ${{ github.event.release.tag_name }}"
          git push

      # add .npmrc
      - run: |
          echo "//registry.npmjs.org/:_authToken=${NPM_AUTH_TOKEN}" > .npmrc

      # publish the packages
      - run: |
          pnpm nx affected -t publish \
          --nxBail \
          --exclude=@warren/source
