name: Prepare Release

on:
  push:
    branches:
      - main
    paths-ignore:
      - CHANGELOG.md
      - README.md
      - LICENSE
      - docs/**

permissions:
  deployments: read
  id-token: write
  contents: read
  actions: read
  pull-requests: write

env:
  NX_CLOUD_ACCESS_TOKEN: ${{ secrets.NX_CLOUD_ACCESS_TOKEN }}

jobs:
  main:
    permissions: write-all
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - uses: asdf-vm/actions/install@v3

      - run: pnpm i

      # test the packages
      - run: pnpm nx run-many --all -t lint typecheck test build

      # create a release
      - uses: release-drafter/release-drafter@v5
        with:
          commitish: ${{ github.sha }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
