name: release

on:
  push:
    branches:
      - main
    paths-ignore:
      - CHANGELOG.md
      - README.md
      - LICENSE
      - docs/**

permissions:
  deployments: read
  id-token: write
  contents: read
  actions: read
  pull-requests: write

env:
  NX_CLOUD_ACCESS_TOKEN: ${{ secrets.NX_CLOUD_ACCESS_TOKEN }}

jobs:
  main:
    permissions: write-all
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - uses: asdf-vm/actions/install@v3

      - run: pnpm i

      - uses: nrwl/nx-set-shas@v4

      - run: pnpm nx affected -t lint typecheck test

      - run: pnpm nx release --skip-publish
